export const images = [
  {
    id: 1,
    first: "/gallery/pic_1.jpg",
    all: [
      "/gallery/pic_1.jpg",
      "/gallery/pic_5.jpg",
      "/gallery/pic_6.jpg",
      "/gallery/pic_8.jpg",
      "/gallery/pic_8.jpg",
      "/gallery/pic_8.jpg",
      "/gallery/pic_8.jpg",
    ],
  },
  {
    id: 2,
    first: "/gallery/pic_2.jpg",
    all: [
      "/gallery/pic_2.jpg",
      "/gallery/pic_7.jpg",
      "/gallery/pic_8.jpg",
      "/gallery/pic_8.jpg",
      "/gallery/pic_8.jpg",
      "/gallery/pic_8.jpg",
    ],
  },
  {
    id: 3,
    first: "/gallery/pic_3.jpg",
    all: [
      "/gallery/pic_3.jpg",
      "/gallery/pic_9.jpg",
      "/gallery/pic_10.jpg",
      "/gallery/pic_8.jpg",
      "/gallery/pic_8.jpg",
      "/gallery/pic_8.jpg",
    ],
  },
  {
    id: 4,
    first: "/gallery/pic_4.jpg",
    all: [
      "/gallery/pic_4.jpg",
      "/gallery/pic_8.jpg",
      "/gallery/pic_9.jpg",
      "/gallery/pic_8.jpg",
      "/gallery/pic_8.jpg",
      "/gallery/pic_8.jpg",
    ],
  },
  {
    id: 5,
    first: "/gallery/pic_4.jpg",
    all: [
      "/gallery/pic_8.jpg",
      "/gallery/pic_9.jpg",
      "/gallery/pic_8.jpg",
      "/gallery/pic_8.jpg",
      "/gallery/pic_8.jpg",
      "/gallery/pic_8.jpg",
    ],
  },
  {
    id: 6,
    first: "/gallery/pic_4.jpg",
    all: [
      "/gallery/pic_8.jpg",
      "/gallery/pic_9.jpg",
      "/gallery/pic_8.jpg",
      "/gallery/pic_8.jpg",
      "/gallery/pic_8.jpg",
      "/gallery/pic_8.jpg",
    ],
  },
];
